server:
  port: 8888
web3:
  http:
    url: https://eth-mainnet.g.alchemy.com/v2/Z_o2kAR_GFo2GnYl3s3RLktflk6TnZtg
  ws:
    url: wss://eth-mainnet.g.alchemy.com/v2/Z_o2kAR_GFo2GnYl3s3RLktflk6TnZtg
contract-address: '0x4E434787789cBC29e5600F7695aA107821B2b81e'